version: "3"
services:
  traefik:
    restart: always
    image: traefik:2.4.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/dynamic.yml:/dynamic.yml:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.mydevproxy.entrypoints=http,https
      - traefik.http.routers.mydevproxy.rule=Host(`traefik.docker.localhost`)
      - traefik.http.routers.mydevproxy.tls=true
      - traefik.http.routers.mydevproxy.service=api@internal

networks:
  default:
    name: inbound