tls:
  options:
    default:
      minVersion: VersionTLS12
    mintls13:
      minVersion: VersionTLS13

  stores:
    default:
      defaultCertificate:
        certFile: /certs/ssl.crt
        keyFile: /certs/ssl.key